name: CI

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manually triggering this workflow"
        required: false
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn
        uses: borales/actions-yarn@v2.3.0

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.13.2"

      - name: Install, Lint, and Build
        run: |
          yarn install
          yarn lint
          yarn pretty
          yarn build
